package game.entities.workers.workerTypes;

public enum WorkerTypeEnum {
    FOOD_GATHERER, ORE_GATHERER, PEAT_GATHERER,
    METAL_GENERATOR, NUTRIENT_GENERATOR,
    POWER_GENERATOR, RESEARCH_GENERATOR,
    SOLDIER_GENERATOR, WORKER_GENERATOR,
    STANDBY;
}
